package com.mrdartsidetm.wasm.util

import com.mrdartsidetm.wasm.data.InstagramAccountEntity
import com.mrdartsidetm.wasm.data.InstagramConversationEntity
import com.mrdartsidetm.wasm.data.InstagramMessageEntity
import java.io.File
import java.text.SimpleDateFormat
import java.util.Locale
import java.util.regex.Pattern

data class InstagramChatIndexItem(
    val title: String,
    val relativeLink: String,
    val folderId: String,
    val isRequest: Boolean
)

object InstagramHtmlParser {

    private val accountGeneratedByRegex = Pattern.compile("Generated by\\s+([\\w\\.\\_\\-]+)\\s+on", Pattern.CASE_INSENSITIVE)
    private val exportDateRegex = Pattern.compile("<aside[^>]*class=\"_aoaa\"[^>]*>([\\s\\S]*?)</aside>", Pattern.CASE_INSENSITIVE)
    private val chatItemRegex = Pattern.compile("<h2 class=\"_a6-h\"><a href=\"([^\"]+)\">([^<]+)</a></h2>")

    private val senderRegex = Pattern.compile("<h2 class=\"[^\"]*\">([^<]+)</h2>")
    private val timeRegex = Pattern.compile("<div class=\"_3-94 _a6-o\">([^<]+)</div>")
    private val audioRegex = Pattern.compile("<audio[^>]*src=\"([^\"]+)\"")
    private val videoRegex = Pattern.compile("<video[^>]*src=\"([^\"]+)\"")
    private val photoRegex = Pattern.compile("<img[^>]*src=\"([^\"]*photos/[^\"]+)\"")
    private val gifRegex = Pattern.compile("<img[^>]*src=\"([^\"]*gifs/[^\"]+)\"")
    private val anyImgRegex = Pattern.compile("<img[^>]*src=\"([^\"]+)\"")
    private val reactionRegex = Pattern.compile("<ul class=\"_a6-q\"><li><span>([^<]+)</span></li></ul>")
    private val sharedLinkRegex = Pattern.compile("<a target=\"_blank\" href=\"(https?://[^\"]+)\">")

    // Date formatter for Instagram timestamps: "Aug 16, 2024 10:58 am"
    private val dateFormat = SimpleDateFormat("MMM d, yyyy h:mm a", Locale.US).apply {
        isLenient = true
    }

    /**
     * Parses the Instagram account information from start_here.html or chats.html.
     */
    fun parseAccountInfo(htmlContent: String, fallbackZipName: String? = null): InstagramAccountEntity {
        var accountName = ""
        var exportDate = ""

        val genMatcher = accountGeneratedByRegex.matcher(htmlContent)
        if (genMatcher.find()) {
            accountName = genMatcher.group(1)?.trim() ?: ""
        }

        if (accountName.isEmpty() && !fallbackZipName.isNullOrBlank()) {
            val zipNameMatcher = Pattern.compile("instagram-([\\w\\.\\_\\-]+)-\\d{4}").matcher(fallbackZipName)
            if (zipNameMatcher.find()) {
                accountName = zipNameMatcher.group(1)?.trim() ?: ""
            }
        }

        if (accountName.isEmpty()) {
            accountName = "Instagram User"
        }

        val dateMatcher = exportDateRegex.matcher(htmlContent)
        if (dateMatcher.find()) {
            val dateBlock = dateMatcher.group(1) ?: ""
            exportDate = dateBlock.replace(Regex("<[^>]+>"), "").trim()
        }

        // Infer friendly display name (e.g. "kajal.23.sinha" -> "Kajal Sinha")
        val inferredDisplayName = formatHandleToDisplayName(accountName)

        return InstagramAccountEntity(
            id = 1,
            accountName = accountName,
            displayName = inferredDisplayName,
            exportDate = exportDate,
            totalConversations = 0,
            totalMessages = 0,
            isDived = false
        )
    }

    /**
     * Formats an Instagram handle into a title-cased display name fallback.
     */
    fun formatHandleToDisplayName(handle: String): String {
        val parts = handle.replace(".", " ").replace("_", " ").split(" ")
        return parts.filter { it.isNotBlank() && it.toIntOrNull() == null }
            .joinToString(" ") { it.replaceFirstChar { c -> c.uppercase() } }
            .ifBlank { handle }
    }

    /**
     * Parses chats.html and returns an index of all conversations.
     */
    fun parseChatsList(chatsHtmlContent: String): List<InstagramChatIndexItem> {
        val list = mutableListOf<InstagramChatIndexItem>()
        val matcher = chatItemRegex.matcher(chatsHtmlContent)
        while (matcher.find()) {
            val relativeLink = matcher.group(1) ?: continue
            val title = unescapeHtml(matcher.group(2) ?: "").trim()
            val isRequest = relativeLink.contains("message_requests/")
            val folderId = extractFolderId(relativeLink)

            list.add(
                InstagramChatIndexItem(
                    title = title,
                    relativeLink = relativeLink,
                    folderId = folderId,
                    isRequest = isRequest
                )
            )
        }
        return list
    }

    /**
     * Extracts folder identifier from a relative path e.g.:
     * "your_instagram_activity/messages/inbox/aadil_1475086853890331/message_1.html" -> "aadil_1475086853890331"
     */
    fun extractFolderId(path: String): String {
        val parent = File(path).parentFile?.name
        return if (!parent.isNullOrBlank() && parent != "inbox" && parent != "message_requests") {
            parent
        } else {
            File(path).nameWithoutExtension
        }
    }

    /**
     * Parses a message_*.html file into a list of InstagramMessageEntity items.
     * Messages are returned in chronological order (oldest first).
     */
    fun parseConversationMessages(
        htmlContent: String,
        conversationId: String,
        accountOwnerDisplayName: String
    ): List<InstagramMessageEntity> {
        val delimiter = "<div class=\"pam _3-95 _2ph- _a6-g uiBoxWhite noborder\">"
        val parts = htmlContent.split(delimiter)
        if (parts.size <= 1) return emptyList()

        val parsedMessages = mutableListOf<InstagramMessageEntity>()

        // Skip parts[0] as it is the HTML header preceding the first message block
        for (i in 1 until parts.size) {
            val rawBlock = parts[i]

            // 1. Sender
            val senderMatcher = senderRegex.matcher(rawBlock)
            val sender = if (senderMatcher.find()) {
                unescapeHtml(senderMatcher.group(1) ?: "").trim()
            } else {
                "Unknown"
            }

            // 2. Timestamp
            val timeMatcher = timeRegex.matcher(rawBlock)
            val timestamp = if (timeMatcher.find()) {
                timeMatcher.group(1)?.trim() ?: ""
            } else {
                ""
            }

            val epochTime = parseTimestampToEpoch(timestamp)

            // 3. Audio, Video, Photo, Gif Media (Extract all items in message block)
            val mediaItems = mutableListOf<Pair<String, String>>()

            val audioMatcher = audioRegex.matcher(rawBlock)
            while (audioMatcher.find()) {
                val path = audioMatcher.group(1)?.trim()
                if (!path.isNullOrBlank()) {
                    mediaItems.add(Pair("audio", path))
                }
            }

            val videoMatcher = videoRegex.matcher(rawBlock)
            while (videoMatcher.find()) {
                val path = videoMatcher.group(1)?.trim()
                if (!path.isNullOrBlank()) {
                    mediaItems.add(Pair("video", path))
                }
            }

            val anyImgMatcher = anyImgRegex.matcher(rawBlock)
            while (anyImgMatcher.find()) {
                val src = anyImgMatcher.group(1)?.trim()
                if (!src.isNullOrBlank() && !src.contains("Instagram-Logo")) {
                    val type = when {
                        src.contains("gifs/") || src.endsWith(".gif", ignoreCase = true) -> "gif"
                        else -> "photo"
                    }
                    if (mediaItems.none { it.second == src }) {
                        mediaItems.add(Pair(type, src))
                    }
                }
            }

            var mediaType: String? = null
            var mediaPath: String? = null
            var mediaPaths: String? = null

            if (mediaItems.isNotEmpty()) {
                val first = mediaItems.first()
                mediaType = if (mediaItems.size > 1) "album" else first.first
                mediaPath = first.second
                mediaPaths = mediaItems.joinToString("|") { "${it.first}:${it.second}" }
            }

            // 4. Reactions
            var reaction: String? = null
            val reactionMatcher = reactionRegex.matcher(rawBlock)
            if (reactionMatcher.find()) {
                reaction = unescapeHtml(reactionMatcher.group(1) ?: "").trim()
            }

            // 5. Shared Reel or Web Link
            var sharedUrl: String? = null
            var sharedTitle: String? = null
            val linkMatcher = sharedLinkRegex.matcher(rawBlock)
            if (linkMatcher.find()) {
                sharedUrl = linkMatcher.group(1)?.trim()
                if (sharedUrl != null && sharedUrl.contains("/reel/")) {
                    if (mediaType == null) {
                        mediaType = "reel"
                    }
                } else if (mediaType == null && sharedUrl != null) {
                    mediaType = "link"
                }
            }

            // 6. Text message extraction
            val contentStartIdx = rawBlock.indexOf("<div class=\"_3-95 _a6-p\">")
            val contentEndIdx = rawBlock.indexOf("<div class=\"_3-94 _a6-o\">")
            var textContent = ""
            if (contentStartIdx != -1 && contentEndIdx != -1 && contentEndIdx > contentStartIdx) {
                val rawContent = rawBlock.substring(contentStartIdx + "<div class=\"_3-95 _a6-p\">".length, contentEndIdx)
                textContent = cleanContentText(rawContent)
            }

            // If shared item had descriptive text, save it as sharedTitle
            if (sharedUrl != null && textContent.isNotBlank()) {
                sharedTitle = textContent
            }

            // Determine Outgoing: sent by account owner or says "You sent an attachment."
            val isYouAttachment = rawBlock.contains("You sent an attachment.")
            val isOutgoing = isYouAttachment || sender.equals(accountOwnerDisplayName, ignoreCase = true)

            // Suppress redundant "(...) sent an attachment." placeholder if real media exists
            if (mediaType != null && (textContent.equals("You sent an attachment.", ignoreCase = true) ||
                        textContent.endsWith("sent an attachment.", ignoreCase = true))) {
                textContent = ""
            }

            parsedMessages.add(
                InstagramMessageEntity(
                    conversationId = conversationId,
                    sender = sender,
                    timestamp = timestamp,
                    epochTime = epochTime,
                    content = textContent,
                    mediaType = mediaType,
                    mediaPath = mediaPath,
                    mediaPaths = mediaPaths,
                    reactions = reaction,
                    sharedUrl = sharedUrl,
                    sharedTitle = sharedTitle,
                    isOutgoing = isOutgoing
                )
            )
        }

        // Instagram exports messages newest to oldest. Reverse to show chronologically (oldest first).
        return parsedMessages.reversed()
    }

    /**
     * Cleans raw HTML content block to extract readable message text.
     */
    private fun cleanContentText(rawHtml: String): String {
        var text = rawHtml
            .replace(Regex("<ul class=\"_a6-q\">[\\s\\S]*?</ul>"), "") // Remove reactions list
            .replace(Regex("<audio[\\s\\S]*?</audio>"), "")             // Remove audio player tags
            .replace(Regex("<video[\\s\\S]*?</video>"), "")             // Remove video player tags
            .replace(Regex("<br\\s*/?>", RegexOption.IGNORE_CASE), "\n") // Line breaks
            .replace(Regex("<[^>]+>"), "")                              // Strip HTML tags

        text = unescapeHtml(text).trim()
        return text
    }

    /**
     * Decodes common HTML character entities.
     */
    fun unescapeHtml(input: String): String {
        if (input.isEmpty()) return ""
        return input
            .replace("&amp;", "&")
            .replace("&#039;", "'")
            .replace("&apos;", "'")
            .replace("&quot;", "\"")
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&#064;", "@")
            .replace("&nbsp;", " ")
    }

    /**
     * Parses Instagram timestamp string ("Aug 16, 2024 10:58 am") to epoch milliseconds.
     */
    fun parseTimestampToEpoch(timestamp: String): Long {
        if (timestamp.isBlank()) return 0L
        return try {
            val date = dateFormat.parse(timestamp)
            date?.time ?: 0L
        } catch (e: Exception) {
            0L
        }
    }
}
