package com.mrdartsidetm.wasm.util

import org.junit.Assert.*
import org.junit.Test
import java.io.File

class InstagramHtmlParserTest {

    private val sampleStartHereHtml = """
        <html><head><title>Your information</title></head><body>
        <div class="_li">
          <aside role="contentinfo" class="_aoaa">Generated by kajal.23.sinha on <time datetime="2026-09-14T11:28Z">Monday, September 14, 2026 at 4:28 AM UTC</time></aside>
        </div>
        </body></html>
    """.trimIndent()

    private val sampleChatsHtml = """
        <html><head><title>Chats</title></head><body>
        <main class="_a706">
          <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder"><h2 class="_a6-h"><a href="your_instagram_activity/messages/inbox/aadil_1475086853890331/message_1.html">Aadil</a></h2></div>
          <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder"><h2 class="_a6-h"><a href="your_instagram_activity/messages/inbox/abhijeetyadav_1424166558982770/message_1.html">Abhijeet Yadav</a></h2></div>
          <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder"><h2 class="_a6-h"><a href="your_instagram_activity/messages/message_requests/kabir_18024019811221262/message_1.html">KABIR&#9889;</a></h2></div>
        </main>
        </body></html>
    """.trimIndent()

    private val sampleMessagesHtml = """
        <html><body><main>
        <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder">
          <h2 class="_3-95 _2pim _a6-h _a6-i">Kajal Sinha</h2>
          <div class="_3-95 _a6-p"><div><div></div><div>Hello there!</div><div></div></div></div>
          <div class="_3-94 _a6-o">Aug 16, 2024 10:58 am</div>
        </div>
        <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder">
          <h2 class="_3-95 _2pim _a6-h _a6-i">Abhijeet Yadav</h2>
          <div class="_3-95 _a6-p"><div><div></div><div>Check this photo</div><div><div><img src="photos/test.jpg" class="_a6_o" /></div></div></div></div>
          <div class="_3-94 _a6-o">Aug 16, 2024 10:59 am</div>
        </div>
        <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder">
          <h2 class="_3-95 _2pim _a6-h _a6-i">Abhijeet Yadav</h2>
          <div class="_3-95 _a6-p"><div><div></div><div><audio src="audio/voice1.mp4" controls="1"></audio></div><div><ul class="_a6-q"><li><span>&#10084;Kajal Sinha</span></li></ul></div></div></div>
          <div class="_3-94 _a6-o">Aug 16, 2024 11:00 am</div>
        </div>
        <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder">
          <h2 class="_3-95 _2pim _a6-h _a6-i">Kajal Sinha</h2>
          <div class="_3-95 _a6-p"><div><div></div><div><video src="videos/clip.mp4" controls="1"></video></div></div></div>
          <div class="_3-94 _a6-o">Aug 16, 2024 11:05 am</div>
        </div>
        <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder">
          <h2 class="_3-95 _2pim _a6-h _a6-i">Abhijeet Yadav</h2>
          <div class="_3-95 _a6-p"><div><div></div><div>Watch this reel</div><div><a target="_blank" href="https://www.instagram.com/reel/C-z4D3xhEPM/">Reel</a></div></div></div>
          <div class="_3-94 _a6-o">Aug 16, 2024 11:10 am</div>
        </div>
        </main></body></html>
    """.trimIndent()

    @Test
    fun testParseAccountInfo() {
        val account = InstagramHtmlParser.parseAccountInfo(sampleStartHereHtml)
        assertEquals("kajal.23.sinha", account.accountName)
        assertEquals("Kajal Sinha", account.displayName)
        assertTrue(account.exportDate.contains("Monday, September 14, 2026"))
    }

    @Test
    fun testParseChatsList() {
        val chats = InstagramHtmlParser.parseChatsList(sampleChatsHtml)
        assertEquals(3, chats.size)

        assertEquals("Aadil", chats[0].title)
        assertEquals("aadil_1475086853890331", chats[0].folderId)
        assertFalse(chats[0].isRequest)

        assertEquals("Abhijeet Yadav", chats[1].title)
        assertEquals("abhijeetyadav_1424166558982770", chats[1].folderId)
        assertFalse(chats[1].isRequest)

        assertEquals("KABIR⚡", chats[2].title)
        assertEquals("kabir_18024019811221262", chats[2].folderId)
        assertTrue(chats[2].isRequest)
    }

    @Test
    fun testParseConversationMessages() {
        val messages = InstagramHtmlParser.parseConversationMessages(
            htmlContent = sampleMessagesHtml,
            conversationId = "abhijeetyadav",
            accountOwnerDisplayName = "Kajal Sinha"
        )
        assertEquals(5, messages.size)

        // 1. Text message
        val msg1 = messages[0]
        assertEquals("Kajal Sinha", msg1.sender)
        assertEquals("Hello there!", msg1.content)
        assertTrue(msg1.isOutgoing)
        assertNull(msg1.mediaType)

        // 2. Photo message
        val msg2 = messages[1]
        assertEquals("Abhijeet Yadav", msg2.sender)
        assertEquals("photo", msg2.mediaType)
        assertEquals("photos/test.jpg", msg2.mediaPath)
        assertFalse(msg2.isOutgoing)

        // 3. Audio / Voice message with reaction
        val msg3 = messages[2]
        assertEquals("Abhijeet Yadav", msg3.sender)
        assertEquals("audio", msg3.mediaType)
        assertEquals("audio/voice1.mp4", msg3.mediaPath)
        assertEquals("❤Kajal Sinha", msg3.reactions)

        // 4. Video message
        val msg4 = messages[3]
        assertEquals("Kajal Sinha", msg4.sender)
        assertEquals("video", msg4.mediaType)
        assertEquals("videos/clip.mp4", msg4.mediaPath)
        assertTrue(msg4.isOutgoing)

        // 5. Shared Reel
        val msg5 = messages[4]
        assertEquals("reel", msg5.mediaType)
        assertEquals("https://www.instagram.com/reel/C-z4D3xhEPM/", msg5.sharedUrl)
    }

    @Test
    fun testRealExportParsingIfAvailable() {
        val testFolder = File("D:/code/temp/instagram-kajal.23.sinha-2026-09-14-sxQHlayj")
        if (!testFolder.exists()) return

        val chatsFile = File(testFolder, "your_instagram_activity/messages/chats.html")
        assertTrue(chatsFile.exists())

        val chats = InstagramHtmlParser.parseChatsList(chatsFile.readText(Charsets.UTF_8))
        assertEquals(27, chats.size)

        val sampleMsgFile = File(testFolder, "your_instagram_activity/messages/inbox/1405380277523017/message_1.html")
        assertTrue(sampleMsgFile.exists())

        val messages = InstagramHtmlParser.parseConversationMessages(
            htmlContent = sampleMsgFile.readText(Charsets.UTF_8),
            conversationId = "1405380277523017",
            accountOwnerDisplayName = "Kajal Sinha"
        )
        assertEquals(493, messages.size)

        // Verify audio was detected
        val audioMsg = messages.find { it.mediaType == "audio" }
        assertNotNull(audioMsg)
        assertTrue(audioMsg!!.mediaPath!!.endsWith(".mp4"))

        // Verify video was detected
        val videoMsg = messages.find { it.mediaType == "video" }
        assertNotNull(videoMsg)
        assertTrue(videoMsg!!.mediaPath!!.endsWith(".mp4"))

        // Verify photo was detected
        val photoMsg = messages.find { it.mediaType == "photo" }
        assertNotNull(photoMsg)
    }

    @Test
    fun testMultiMediaGrouping() {
        val multiMediaHtml = """
            <html><body><main>
            <div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder">
              <h2 class="_3-95 _2pim _a6-h _a6-i">Deepanjali......</h2>
              <div class="_3-95 _a6-p">
                <div><div><a href="photos/p1.jpg"><img src="photos/p1.jpg" /></a></div></div>
                <div><div><a href="photos/p2.jpg"><img src="photos/p2.jpg" /></a></div></div>
                <div><div><video src="videos/v1.mp4"></video></div></div>
              </div>
              <div class="_3-94 _a6-o">Aug 16, 2024 10:58 am</div>
            </div>
            </main></body></html>
        """.trimIndent()

        val messages = InstagramHtmlParser.parseConversationMessages(multiMediaHtml, "deepanjali", "Kajal Sinha")
        assertEquals(1, messages.size)
        val msg = messages[0]
        assertEquals("album", msg.mediaType)
        val list = msg.getMediaList()
        assertEquals(3, list.size)
        assertEquals("photo", list[0].first)
        assertEquals("photos/p1.jpg", list[0].second)
        assertEquals("photo", list[1].first)
        assertEquals("photos/p2.jpg", list[1].second)
        assertEquals("video", list[2].first)
        assertEquals("videos/v1.mp4", list[2].second)
    }
}
